/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#ffffff",
        "on-primary": "#000000",
        "accent-blue": "#0099ff",
        ink: "#ffffff",
        "ink-muted": "#999999",
        canvas: "#090909",
        "surface-1": "#141414",
        "surface-2": "#1c1c1c",
        hairline: "#262626",
        "hairline-soft": "#1a1a1a",
        "inverse-canvas": "#ffffff",
        "inverse-ink": "#000000",
        "gradient-magenta": "#d44df0",
        "gradient-violet": "#6a4cf5",
        "gradient-orange": "#ff7a3d",
        "gradient-coral": "#ff5577",
        "semantic-success": "#22c55e",
        
        // Tailwind defaults mapped
        background: "#090909",
        foreground: "#ffffff",
        card: "#141414",
        "card-foreground": "#ffffff",
        popover: "#141414",
        "popover-foreground": "#ffffff",
        muted: "#141414",
        "muted-foreground": "#999999",
        accent: "#1c1c1c",
        "accent-foreground": "#ffffff",
        border: "#262626",
        input: "#141414",
        ring: "#0099ff",
      },
      fontFamily: {
        sans: ["Inter", "Inter Variable", "sans-serif"],
        display: ["GT Walsheim Medium", "Inter", "sans-serif"],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "10px",
        lg: "15px",
        xl: "20px",
        xxl: "30px",
        pill: "100px",
        full: "9999px",
      },
      spacing: {
        hair: "1px",
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "15px",
        lg: "20px",
        xl: "30px",
        xxl: "40px",
        section: "96px",
      }
    },
  },
  plugins: [],
}
