import simpleGit, { SimpleGit } from 'simple-git'
import fs from 'fs'
import path from 'path'
import { AnalysisIssue } from '../../shared/ipc'

export interface ApplyResult {
  branch: string
  filesChanged: string[]
  commitHash: string
}

export async function applyAcceptedIssues(
  projectPath: string,
  issues: AnalysisIssue[]
): Promise<ApplyResult> {
  const git: SimpleGit = simpleGit(projectPath)

  // Garante que é um repo git
  const isRepo = await git.checkIsRepo()
  if (!isRepo) throw new Error('O projecto não é um repositório Git.')

  // Cria branch nova
  const timestamp = Date.now()
  const branch = `refract/fix-${timestamp}`
  await git.checkoutLocalBranch(branch)

  const filesChanged: string[] = []

  for (const issue of issues) {
    if (!issue.lines.after.length) continue
    try {
      const content = fs.readFileSync(issue.filePath, 'utf-8')
      const original = content.split('\n')

      // Substitui as linhas do range pelo after
      const before = original.slice(0, issue.lineStart - 1)
      const after  = original.slice(issue.lineEnd)
      const newContent = [...before, ...issue.lines.after, ...after].join('\n')

      fs.writeFileSync(issue.filePath, newContent, 'utf-8')
      filesChanged.push(issue.filePath)
    } catch (err) {
      console.error(`Failed to apply issue ${issue.id}:`, err)
    }
  }

  if (filesChanged.length === 0) throw new Error('Nenhum ficheiro foi alterado.')

  // Stage + commit
  const relativeFiles = filesChanged.map(f => path.relative(projectPath, f))
  try {
    await git.add(relativeFiles)
  } catch (err) {
    console.error('Git add failed. Some files might be ignored or outside the repo:', err)
    // Try adding files one by one to avoid complete failure
    for (const f of relativeFiles) {
      try {
        await git.add(f)
      } catch {}
    }
  }
  const commit = await git.commit(
    `refract: improve code quality\n\n` +
    `Applied ${issues.length} suggestion(s):\n` +
    issues.map(i => `- ${i.file}: ${i.problem}`).join('\n') +
    `\n\nGenerated by Refract — all changes reviewed and approved by developer.`
  )

  return {
    branch,
    filesChanged,
    commitHash: commit.commit,
  }
}
