import type { FileIssue, DiffLine, SnippetPair } from './types'

export const FILE_ISSUES: FileIssue[] = [
  { id: 1, file: 'Dashboard.tsx',     problem: 'Oversized component' },
  { id: 2, file: 'AuthProvider.tsx',  problem: 'any types on props' },
  { id: 3, file: 'useProjectData.ts', problem: 'Dead useState' },
  { id: 4, file: 'ProjectCard.tsx',   problem: 'Repeated Tailwind' },
  { id: 5, file: 'SettingsPage.tsx',  problem: 'Missing JSDoc' },
]

export const BEFORE_LINES: DiffLine[] = [
  { num:  1, type: 'normal',  content: "import React, { useState, useEffect } from 'react'" },
  { num:  2, type: 'normal',  content: '' },
  { num:  3, type: 'removed', content: 'const Dashboard = ({ data1, data2, tempVar }: any) => {' },
  { num:  4, type: 'removed', content: '  const [val1, setVal1] = useState<any>(null)' },
  { num:  5, type: 'removed', content: '  const [val2, setVal2] = useState<any>(null)' },
  { num:  6, type: 'removed', content: '  const [val3, setVal3] = useState<any>(false)' },
  { num:  7, type: 'removed', content: '  const [val4, setVal4] = useState<any>([])' },
  { num:  8, type: 'removed', content: '  const [val5, setVal5] = useState<any>({})' },
  { num:  9, type: 'removed', content: '  const [loading, setLoading] = useState<any>(false)' },
  { num: 10, type: 'normal',  content: '' },
  { num: 11, type: 'normal',  content: '  useEffect(() => {' },
  { num: 12, type: 'removed', content: "    fetch('/api/data').then((r: any) => r.json())" },
  { num: 13, type: 'removed', content: '      .then((d: any) => { setVal1(d.user); setVal2(d.projects) })' },
  { num: 14, type: 'normal',  content: '  }, [])' },
  { num: 15, type: 'normal',  content: '' },
  { num: 16, type: 'removed', content: '  const handleClick2 = () => {' },
  { num: 17, type: 'removed', content: '    setVal3(!val3)' },
  { num: 18, type: 'removed', content: '    setVal4([...val4, tempVar])' },
  { num: 19, type: 'normal',  content: '  }' },
  { num: 20, type: 'normal',  content: '' },
  { num: 21, type: 'normal',  content: '  return (' },
  { num: 22, type: 'removed', content: '    <div className="flex flex-col w-full h-full">' },
  { num: 23, type: 'removed', content: '      <div className="flex items-center justify-between p-4">' },
  { num: 24, type: 'removed', content: '        <h1 className="text-xl font-bold">{val1?.name}</h1>' },
  { num: 25, type: 'removed', content: '        <button onClick={handleClick2}>Toggle</button>' },
  { num: 26, type: 'removed', content: '      </div>' },
  { num: 27, type: 'removed', content: '      <div className="grid grid-cols-3 gap-4 p-4">' },
  { num: 28, type: 'removed', content: '        {val2?.map((item: any, idx: any) => (' },
  { num: 29, type: 'removed', content: '          <div key={idx}><span>{item.name}</span>' },
  { num: 30, type: 'removed', content: '            {item.tasks?.map((t: any, i: any) => (' },
  { num: 31, type: 'removed', content: '              <div key={i}>{t.title}</div>' },
  { num: 32, type: 'removed', content: '            ))}</div>' },
  { num: 33, type: 'removed', content: '        ))}' },
  { num: 34, type: 'removed', content: '      </div>' },
  { num: 35, type: 'removed', content: '      {val3 && <div className="modal"><span>{val5?.message}</span></div>}' },
  { num: 36, type: 'normal',  content: '    </div>' },
  { num: 37, type: 'normal',  content: '  )' },
  { num: 38, type: 'normal',  content: '}' },
  { num: 39, type: 'normal',  content: '' },
  { num: 40, type: 'removed', content: 'export default Dashboard' },
]

export const AFTER_LINES: DiffLine[] = [
  { num:  1, type: 'normal', content: "import React from 'react'" },
  { num:  2, type: 'added',  content: "import { DashboardHeader } from './DashboardHeader'" },
  { num:  3, type: 'added',  content: "import { ProjectGrid } from './ProjectGrid'" },
  { num:  4, type: 'added',  content: "import { NotificationModal } from './NotificationModal'" },
  { num:  5, type: 'added',  content: "import { useDashboardData } from '../hooks/useDashboardData'" },
  { num:  6, type: 'normal', content: '' },
  { num:  7, type: 'added',  content: '// Separates routing, layout, and data from UI rendering' },
  { num:  8, type: 'added',  content: 'interface DashboardProps {' },
  { num:  9, type: 'added',  content: '  userId: string' },
  { num: 10, type: 'added',  content: '}' },
  { num: 11, type: 'normal', content: '' },
  { num: 12, type: 'added',  content: 'export const Dashboard: React.FC<DashboardProps> = ({ userId }) => {' },
  { num: 13, type: 'added',  content: '  // All state & fetching lifted into a focused custom hook' },
  { num: 14, type: 'added',  content: '  const { user, projects, notification,' },
  { num: 15, type: 'added',  content: '    isModalOpen, toggleModal } = useDashboardData(userId)' },
  { num: 16, type: 'normal', content: '' },
  { num: 17, type: 'normal', content: '  return (' },
  { num: 18, type: 'added',  content: '    <div className="flex flex-col w-full h-full">' },
  { num: 19, type: 'added',  content: '      {/* Each sub-component owns a single responsibility */}' },
  { num: 20, type: 'added',  content: '      <DashboardHeader user={user} onToggle={toggleModal} />' },
  { num: 21, type: 'added',  content: '      <ProjectGrid projects={projects} />' },
  { num: 22, type: 'normal', content: '      {isModalOpen && (' },
  { num: 23, type: 'added',  content: '        <NotificationModal' },
  { num: 24, type: 'added',  content: '          message={notification?.message}' },
  { num: 25, type: 'added',  content: '          onClose={toggleModal}' },
  { num: 26, type: 'added',  content: '        />' },
  { num: 27, type: 'normal', content: '      )}' },
  { num: 28, type: 'normal', content: '    </div>' },
  { num: 29, type: 'normal', content: '  )' },
  { num: 30, type: 'normal', content: '}' },
]

export const SUCCESS_SNIPPETS: SnippetPair[] = [
  {
    id: 1,
    label: 'Dead state removed',
    before: [
      { num: 1, type: 'removed', content: 'const [val1, setVal1] = useState<any>(null)' },
      { num: 2, type: 'removed', content: 'const [val2, setVal2] = useState<any>([])' },
    ],
    after: [
      { num: 1, type: 'added', content: 'const { user, projects } = useDashboardData(userId)' },
    ],
  },
  {
    id: 2,
    label: 'Type safety restored',
    before: [
      { num: 1, type: 'removed', content: 'const Dashboard = ({ data1 }: any) => {' },
    ],
    after: [
      { num: 1, type: 'added', content: 'interface DashboardProps { userId: string }' },
      { num: 2, type: 'added', content: 'const Dashboard: React.FC<DashboardProps> = ({ userId }) => {' },
    ],
  },
]
